networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  victoriametrics:
    cap_drop:
      - ALL
    command:
      - -retentionPeriod=180d
    image: docker.io/victoriametrics/victoria-metrics:v1.144.0@sha256:dc030542eb0cd262287c9ec32e5867f8dcccc0efd5906c10f7fc8176c53d34d7
    labels:
      monitoring.metrics.port: 8428
      traefik.enable: true
      traefik.http.routers.victoriametrics.entrypoints: http
      traefik.http.routers.victoriametrics.rule: Host(`victoriametrics.zarantonello.net`)
      traefik.http.services.victoriametrics.loadbalancer.server.port: 8428
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 34866:34866
    volumes:
      - $HOME/volumes/victoriametrics:/victoria-metrics-data
