configs:
  blocky:
    file: ./_configs/blocky.yaml

networks:
  alloy_default:
    external: true

services:
  blocky:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: blocky
        target: /app/config.yml
    extends:
      file: _patches/${HOSTNAME}.yaml
      service: blocky
    healthcheck:
      disable: true
    image: ghcr.io/0xerr0r/blocky:v0.32.1@sha256:19d856a00569f24b6e295d95feec87d2c07c92f4ee60c3bf2324f1e4b5348e97
    labels:
      monitoring.logs: true
      monitoring.metrics.port: 8080
    networks:
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 21575:21575
