configs:
  blocky:
    file: ./_configs/blocky.yaml

networks:
  alloy_default:
    external: true

services:
  blocky:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: blocky
        target: /app/config.yml
    extends:
      file: _patches/${HOSTNAME}.yaml
      service: blocky
    healthcheck:
      disable: true
    image: ghcr.io/0xerr0r/blocky:v0.33.0@sha256:96c4ee1d4abee3e81475796403ffde0dfd0c53a6e263e2c35c867ba5563535d4
    labels:
      monitoring.logs: true
      monitoring.metrics.port: 8080
    networks:
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 21575:21575
