concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.74@sha256:14ce86e703166fab76bdb5ff94b06627b7d21ad461c34ee51662540904ab0d14
    runs-on: srv-generic
    steps:
      - run: cz check --message '${{ forge.event.pull_request.title }}'

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
