concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.44@sha256:05fb89dc876c7d05f0340c7c4a897d3657531e602c35baa17a8f116339d46772
    runs-on: srv-generic
    steps:
      - run: cz check --message '${{ forge.event.pull_request.title }}'

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
