concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-prettier:
    container:
      image: git.zarantonello.dev/infra/ci:v3.0.1@sha256:51d22078988307f1fafe76d3242c891f10b62d4e7729c6d411019bec20c0e08f
    name: Check files formatting
    runs-on: srv-generic
    steps:
      - name: Clone the repository
        uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Run prettier
        run: prettier --check .

name: check-prettier.yaml

"on":
  pull_request:
    branches:
      - main
