concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.74@sha256:14ce86e703166fab76bdb5ff94b06627b7d21ad461c34ee51662540904ab0d14
    runs-on: srv-generic
    steps:
      - uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: yamllint .

"on":
  pull_request:
    branches:
      - main
