concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-yamllint:
    container:
      image: git.zarantonello.dev/infra/ci:v2.4.8@sha256:ecd8252e17bb1f713b9ccd5f6d387097b35604df07e9a98c7cd74f7064f44671
    runs-on: srv-generic
    steps:
      - uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: yamllint .

"on":
  pull_request:
    branches:
      - main
