concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-prettier:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.84@sha256:62d82e13c87e895d29c145f7a7e1494998c4c9584c0745f5db92feb8ce3639a4
    runs-on: srv-generic
    steps:
      - uses: https://data.forgejo.org/actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: prettier --check .

"on":
  pull_request:
    branches:
      - main
