concurrency:
  cancel-in-progress: true
  group: ${{ forge.ref }}-${{ forge.workflow }}

jobs:
  check-commitizen:
    container:
      image: git.zarantonello.dev/infra/ci:v2.3.38@sha256:be2c8aa4e64a5aee48799f0fa5d531312132632199ab48126c52bdfc8f265ac1
    runs-on: srv-generic
    steps:
      - run: cz check --message '${{ forge.event.pull_request.title }}'

"on":
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
