jobs:
  respond:
    container:
      image: git.zarantonello.dev/projects/forgejo-agent:ci@sha256:9ed12faa59d24bcd8a5d9d550415a09a7965e6274b5fc15be10504bb79d116bb
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
    name: LLM Bot response generation
    runs-on: srv-0-thi-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p $HOME/.pi/agent/
          echo '{"providers":{"llama-server":{"baseUrl":"http://llama.zarantonello.dev/v1","api":"openai-completions","apiKey":"llama","models":[{"id":"Qwen3.6-35B-A3B","contextWindow":65536}]}}}' > $HOME/.pi/agent/models.json
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@d862d6a7fb44eb819303cde0a5939b2fea46e473 # v1.8.6
        with:
          auth-token: ${{ secrets.AGENT_TOKEN }}
          auth-username: llm-bot
          git-author: LLM [bot]
          git-email: llm-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
