jobs:
  respond:
    container:
      image: git.zarantonello.dev/projects/forgejo-agent:ci@sha256:894bea625a889c7c5b3ef8fb4090961e169c6d1a4f7828a167cad9e8ecfd7bfc
      # The composite action in action.yaml can save the binary to speed up
      # subsequent runs.
      volumes:
        - forgejo-runner-cache-forgejo-agent:/cache/forgejo-agent
    name: LLM Bot response generation
    runs-on: srv-0-thi-home
    steps:
      - name: Configure pi
        run: |
          mkdir -p $HOME/.pi/agent/
          echo '{"providers":{"llama-server":{"baseUrl":"http://llama.zarantonello.dev/v1","api":"openai-completions","apiKey":"llama","models":[{"id":"Qwen3.6-35B-A3B","contextWindow":65536}]}}}' > $HOME/.pi/agent/models.json
      - name: Generate response
        uses: https://git.zarantonello.dev/projects/forgejo-agent@5ecd9c29f4f6875e31aa64996f3f4b9dad18f991 # v1.8.5
        with:
          auth-token: ${{ secrets.AGENT_TOKEN }}
          auth-username: llm-bot
          git-author: LLM [bot]
          git-email: llm-bot@git.zarantonello.dev

name: forgejo-agent

"on":
  issue_comment:
    types:
      - created
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - review_requested
