networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  machine-learning:
    cap_drop:
      - ALL
    image: ghcr.io/immich-app/immich-machine-learning:v2.5.6@sha256:b213fa3c82d27a21a299c46ffbb38a091f18384db1ad67d409a3b34fe0fce556
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=56186,gid=56186
      - /.cache:uid=56186,gid=56186
      - /.config:uid=56186,gid=56186
    user: 56186:56186
    volumes:
      - $HOME/volumes/immich/machine-learning-cache:/cache

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      # Configures the user used for healthchecking.
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 60s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: ghcr.io/tensorchord/vchord-postgres:pg18-v1.0.0@sha256:24a51a291b2f7c30214be566a7ad8474ee02de8947482084297d263520a97e16
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=999,gid=999
      - /var/run/postgresql:uid=999,gid=999
    # User has to be 999, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 999:999
    volumes:
      - $HOME/volumes/immich/postgres:/var/lib/postgresql
    # Sets correct workdir when exec-ing to create backup dumps.
    working_dir: /var/lib/postgresql

  redis:
    cap_drop:
      - ALL
    healthcheck:
      interval: 60s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:8.6.0@sha256:7b6fb55d8b0adcd77269dc52b3cfffe5f59ca5d43dec3c90dbe18aacce7942e1
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 9243:9243
    volumes:
      - $HOME/volumes/immich/redis:/data

  server:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      DB_DATABASE_NAME: ${POSTGRES_DB}
      DB_HOSTNAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      IMMICH_TELEMETRY_INCLUDE: all
      REDIS_HOSTNAME: redis
    image: ghcr.io/immich-app/immich-server:v2.5.6@sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a
    labels:
      monitoring.metrics.port: 8081
      traefik.enable: true
      # The app connects via http, it's less resource intensive and encryption
      # is provided by tailscale anyway.
      traefik.http.routers.immich.entrypoints: https,http
      traefik.http.routers.immich.rule: Host(`photos.zarantonello.net`)
      traefik.http.routers.immich.service: immich
      traefik.http.services.immich.loadbalancer.server.port: 2283
    networks:
      - alloy_default
      - default
      - traefik_default
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 5551:5551
    volumes:
      - $HOME/volumes/immich/data:/usr/src/app/upload
