networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  machine-learning:
    cap_drop:
      - ALL
    image: ghcr.io/immich-app/immich-machine-learning:v2.6.3@sha256:33b17015c3d14f2565e9b8cd36b48a70027b14b5cd20da7fbfff21a370b0309c
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=56186,gid=56186
      - /.cache:uid=56186,gid=56186
      - /.config:uid=56186,gid=56186
    user: 56186:56186
    volumes:
      - $HOME/volumes/immich/machine-learning-cache:/cache

  postgres:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      # Configures the user used for healthchecking.
      PGUSER: ${POSTGRES_USER}
    healthcheck:
      interval: 60s
      retries: 5
      test:
        - CMD
        - pg_isready
      timeout: 5s
    image: ghcr.io/tensorchord/vchord-postgres:pg18-v1.1.1@sha256:700ff05ebdc7e4afd4dd8442e0684293046c3833677fec326550000a04cf8a91
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=999,gid=999
      - /var/run/postgresql:uid=999,gid=999
    # User has to be 999, otherwise the container tries to chown the postgres
    # volume but fails due to insufficient permissions.
    user: 999:999
    volumes:
      - $HOME/volumes/immich/postgres:/var/lib/postgresql
    # Sets correct workdir when exec-ing to create backup dumps.
    working_dir: /var/lib/postgresql

  redis:
    cap_drop:
      - ALL
    healthcheck:
      interval: 60s
      retries: 5
      test:
        - CMD
        - redis-cli
        - ping
      timeout: 5s
    image: docker.io/library/redis:8.6.2@sha256:970b561d234882c50495c69ffae28f94b6ad8d526f91f9b4ccdd8031466e11a2
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 9243:9243
    volumes:
      - $HOME/volumes/immich/redis:/data

  server:
    cap_drop:
      - ALL
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    environment:
      DB_DATABASE_NAME: ${POSTGRES_DB}
      DB_HOSTNAME: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_USERNAME: ${POSTGRES_USER}
      IMMICH_TELEMETRY_INCLUDE: all
      REDIS_HOSTNAME: redis
    image: ghcr.io/immich-app/immich-server:v2.6.3@sha256:0cc1f82953d9598eb9e9dd11cbde1f50fe54f9c46c4506b089e8ad7bfc9d1f0c
    labels:
      monitoring.metrics.port: 8081
      traefik.enable: true
      # The app connects via http, it's less resource intensive and encryption
      # is provided by tailscale anyway.
      traefik.http.routers.immich.entrypoints: https,http
      traefik.http.routers.immich.rule: Host(`photos.zarantonello.net`)
      traefik.http.services.immich.loadbalancer.server.port: 2283
    networks:
      - alloy_default
      - default
      - traefik_default
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 5551:5551
    volumes:
      - $HOME/volumes/immich/data:/usr/src/app/upload
