configs:
  runner:
    file: ./_configs/config.yaml

networks:
  forgejo-runner_default:
    name: forgejo-runner_default

services:
  runner:
    cap_drop:
      - ALL
    configs:
      - source: runner
        target: /etc/runner/config.yaml
    entrypoint:
      - forgejo-runner
      - daemon
      - --url=https://git.zarantonello.dev
      - --uuid=${RUNNER_UUID}
      - --token-url=file:///data/token
      - --label=${NODE_NAME}:docker://busybox
      - --label=srv-${NODE_TYPE}:docker://busybox
      - --label=srv-generic:docker://busybox
      - --config=/etc/runner/config.yaml
    env_file: .env
    extra_hosts:
      git.zarantonello.dev: 100.79.164.85
    group_add:
      - 991
    image: data.forgejo.org/forgejo/runner:12.10.0@sha256:d708348726d2358236ada4f134c721e7f9925c511d807ff9332a12c68e55a323
    networks:
      - forgejo-runner_default
    read_only: true
    restart: always
    tmpfs:
      - /tmp:uid=4880,gid=4880
    user: 4880:4880
    volumes:
      - $HOME/volumes/forgejo-runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
