networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  victorialogs:
    cap_drop:
      - ALL
    command:
      - -retentionPeriod=30d
    image: docker.io/victoriametrics/victoria-logs:v1.48.0@sha256:2c15cfb7902d3f2756efbdf120dbeabb9dca45457addf32f7071236b4c6feb8e
    labels:
      monitoring.metrics.port: 9428
      traefik.enable: true
      traefik.http.routers.victorialogs.entrypoints: http
      traefik.http.routers.victorialogs.rule: Host(`victorialogs.zarantonello.net`)
      traefik.http.services.victorialogs.loadbalancer.server.port: 9428
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 54433:54433
    volumes:
      - $HOME/volumes/victorialogs:/victoria-logs-data
