configs:
  traefik:
    file: ./_configs/traefik.yml

networks:
  alloy_default:
    external: true
  traefik_default:
    name: traefik_default

services:
  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
    env_file: .env
    extends:
      file: _patches/${HOSTNAME}.yaml
      service: traefik
    group_add:
      - 991
    image: docker.io/library/traefik:v3.7.10@sha256:617c253c5d960e257ec153d582cc62f191461baba6863bd6b498ae062d3d5c19
    labels:
      monitoring.metrics.port: 8082
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - traefik-certificates:/var/lib/traefik
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik-certificates: {}
