configs:
  traefik:
    file: ./_configs/traefik.yml

networks:
  alloy_default:
    external: true
  traefik_default:
    name: traefik_default

services:
  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
    env_file: .env
    group_add:
      - 991
    image: docker.io/library/traefik:v3.7.5@sha256:e4d98158c01ad752fc1071d4e9573788747230d902cdde00a772516e692d07c9
    labels:
      monitoring.metrics.port: 8082
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - traefik-certificates:/var/lib/traefik
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik-certificates: {}
