configs:
  traefik:
    file: ./_configs/traefik.yml

networks:
  alloy_default:
    external: true
  traefik_default:
    name: traefik_default

services:
  traefik:
    cap_drop:
      - ALL
    configs:
      - source: traefik
        target: /etc/traefik/traefik.yml
    env_file: .env
    group_add:
      - 991
    image: docker.io/library/traefik:v3.7.8@sha256:4299bbed850421258fc5448c2e0e6ad350981d4d335a68de11b92448aedbefe5
    labels:
      monitoring.metrics.port: 8082
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 51664:51664
    volumes:
      - traefik-certificates:/var/lib/traefik
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  traefik-certificates: {}
