configs:
  alloy:
    file: ./_configs/config.alloy

networks:
  alloy_default:
    name: alloy_default

services:
  alloy:
    cap_drop:
      - ALL
    command:
      - run
      - --server.http.listen-addr=[::]:12345
      - --storage.path=/var/tmp/alloy
      - --server.http.enable-pprof=false
      - /etc/alloy/config.alloy
    configs:
      - source: alloy
        target: /etc/alloy/config.alloy
    environment:
      NODE_HOSTNAME: ${HOSTNAME}
    extra_hosts:
      - hosts.docker.internal:host-gateway
    group_add:
      - 991
    image: docker.io/grafana/alloy:v1.13.0@sha256:6616111d70b3c75d5aa177e0584a523403eaba0eb3b177cb387302c2206d5221
    labels:
      monitoring.logs: true
      monitoring.metrics.port: 12345
    networks:
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 58210:58210
    volumes:
      - alloy-wal:/var/tmp/alloy
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  alloy-wal: {}
