networks:
  traefik_default:
    external: true

services:
  actual:
    cap_drop:
      - ALL
    image: docker.io/actualbudget/actual-server:latest@sha256:ea21a0b6243797d35ef6c4a8713c87efaba8fec3b3663220fa3af61f352fba5e
    labels:
      traefik.enable: true
      traefik.http.routers.actual.entrypoints: https
      traefik.http.routers.actual.rule: Host(`actual.zarantonello.net`)
      traefik.http.services.actual.loadbalancer.server.port: 5006
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 14638:14638
    volumes:
      - $HOME/volumes/actual:/data
