networks:
  traefik_default:
    external: true

services:
  actual:
    cap_drop:
      - ALL
    image: docker.io/actualbudget/actual-server:latest@sha256:74385f8067f401e61f0be9e343c471705c42dfaa195295c40c5b2f15f4dcc9d4
    labels:
      traefik.enable: true
      traefik.http.routers.actual.entrypoints: https
      traefik.http.routers.actual.rule: Host(`actual.zarantonello.net`)
      traefik.http.services.actual.loadbalancer.server.port: 5006
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 14638:14638
    volumes:
      - $HOME/volumes/actual:/data
