services:
  whisper:
    command: |
      --host 0.0.0.0
      --port 8079
      -pp
      --model /models/ggml-large-v3-turbo.bin
    devices:
      - /dev/dri
    entrypoint: whisper-server
    image: ghcr.io/ggml-org/whisper.cpp:main-vulkan@sha256:eb9f6c9c09f880c4e844f18f5726b285f908b14618b5ca91469a03c46c8b7f42
    ports:
      - 127.0.0.1:8079:8079
    read_only: true
    restart: always
    user: 1000:1000
    volumes:
      - $HOME/.local/share/whisper-server/models:/models:z,ro
      - $HOME/.cache/whisper-server:/home/ubuntu/.cache:z,U
