services:
  whisper:
    command: |
      --host 0.0.0.0
      --port 8079
      -pp
      --model /models/ggml-large-v3-turbo.bin
    devices:
      - /dev/dri
    entrypoint: whisper-server
    image: ghcr.io/ggml-org/whisper.cpp:main-vulkan@sha256:3bbf3e6e9c3899f0380a451495a3b900ac6ecdcc4ed5c8d62fb66f99db1ee57a
    ports:
      - 127.0.0.1:8079:8079
    read_only: true
    restart: always
    user: 1000:1000
    volumes:
      - $HOME/.local/share/whisper-server/models:/models:z,ro
      - $HOME/.cache/whisper-server:/home/ubuntu/.cache:z,U
