services:
  devcontainer:
    environment:
      # Tell sops where to find the secret key for age decryption.
      SOPS_AGE_KEY_FILE: /workspace/.sops.key
    image: git.zarantonello.dev/infra/ci:v2.3.47@sha256:bd8d64d8755a56dc39c7fa57aabb6bd28a39079bc2a8dab9e5365bc76014f4e6
    volumes:
      - ..:/workspace:cached
