services:
  llama:
    command: |
      -b 1024 -ub 256 --no-warmup
      --models-preset /models/config.ini --models-max 1
    devices:
      - /dev/dri
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan@sha256:8e580371dbe4ef2b58aa758154c728e22b08cb5fd37ed6731b6616cecd6e4678
    ports:
      - 127.0.0.1:8080:8080
    read_only: true
    restart: always
    user: 1000:1000
    volumes:
      - $HOME/.local/share/llama-server/models:/models
      - $HOME/.cache/llama-server:/home/ubuntu/.cache
