services:
  llama:
    command: |
      -b 1024 -ub 256
      --flash-attn
      --no-warmup
      --models-max 1
      --models-preset /models/config.ini
    devices:
      - /dev/dri
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan@sha256:0236196ce37819436ab1d25af8fd33ae6a4c49365870e38d10c3447a3b44c824
    ports:
      - 127.0.0.1:8080:8080
    read_only: true
    restart: always
    user: 1000:1000
    volumes:
      - $HOME/.local/share/llama-server/models:/models
      - $HOME/.cache/llama-server:/home/ubuntu/.cache
