services:
  llama:
    command: |
      -b 1024 -ub 256
      --models-max 1
      --models-preset /etc/llama-server/models.ini
    devices:
      - /dev/dri
    image: ghcr.io/ggml-org/llama.cpp:server-vulkan@sha256:8944f2119c0a74eaed358560b602561714b9a5108ed6ca3a8a7ec3f9819d47a6
    ports:
      - 127.0.0.1:8080:8080
    read_only: true
    restart: always
    user: 1000:1000
    volumes:
      - ./_configs/models.ini:/etc/llama-server/models.ini:z,ro
      - $HOME/.local/share/llama-server:/var/lib/llama-server:z,ro
      - $HOME/.cache/llama-server:/home/ubuntu/.cache:z,U
