services:
  node-exporter:
    cap_drop:
      - ALL
    command:
      - --path.rootfs=/host
    image: quay.io/prometheus/node-exporter:v1.11.1@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
    labels:
      monitoring.metrics.port: 9100
    network_mode: host
    pid: host
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 3095:3095
    volumes:
      - /:/host:ro,rslave
