# Example /etc/fstab with 4 disks:
#
# ## garage 0 ##
#
# # sda
# UUID=your-fs-uuid /home/user/volumes/garage/0/data/sda btrfs subvol=@data,nofail 0 0
#
# # sdb
# UUID=your-fs-uuid /home/user/volumes/garage/0/data/sdb btrfs subvol=@data,nofail 0 0
# UUID=your-fs-uuid /home/user/volumes/garage/0/metadata btrfs subvol=@metadata,nofail 0 0
#
# ## garage 1 ##
#
# # sdc
# UUID=your-fs-uuid /home/user/volumes/garage/1/data/sdc btrfs subvol=@data,nofail 0 0
# UUID=your-fs-uuid /home/user/volumes/garage/1/metadata btrfs subvol=@metadata,nofail 0 0
#
# # sdd
# UUID=your-fs-uuid /home/user/volumes/garage/1/data/sdd btrfs subvol=@data,nofail 0 0
#
# ## garage snapshots ##
#
# # sda
# UUID=your-fs-uuid /home/user/volumes/garage/0/snapshots btrfs subvol=@snapshots,nofail 0 0
#
# # sdd
# UUID=your-fs-uuid /home/user/volumes/garage/1/snapshots btrfs subvol=@snapshots,nofail 0 0

configs:
  garage-0:
    file: ./_configs/garage-0.toml
  garage-1:
    file: ./_configs/garage-1.toml

networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  garage-0:
    build: .
    cap_drop:
      - ALL
    configs:
      - source: garage-0
        target: /etc/garage.toml
    env_file: .env
    healthcheck:
      interval: 60s
      retries: 5
      test:
        - CMD
        - wget
        - -q
        - -O
        - /dev/stdout
        - http://localhost:3903/health
      timeout: 5s
    labels:
      monitoring.metrics.port: 3903
      traefik.enable: true
      traefik.http.routers.garage-s3.entrypoints: http,https
      traefik.http.routers.garage-s3.rule: Host(`s3.zarantonello.dev`)
      traefik.http.routers.garage-s3.service: garage-s3
      traefik.http.services.garage-s3.loadbalancer.server.port: 3900
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 18781:18781
    volumes:
      - $HOME/volumes/garage/0:/var/lib/garage

  garage-1:
    configs:
      - source: garage-1
        target: /etc/garage.toml
    extends:
      service: garage-0
    volumes:
      - $HOME/volumes/garage/1:/var/lib/garage
