networks:
  traefik_default:
    external: true

services:
  rustfs:
    cap_drop:
      - ALL
    environment:
      RUSTFS_CONSOLE_ENABLE: true
      RUSTFS_VOLUMES: /data/{0...3}
    image: git.zarantonello.dev/infra/rustfs:v1.0.2
    labels:
      traefik.enable: true
      traefik.http.routers.rustfs-console.entrypoints: http,https
      traefik.http.routers.rustfs-console.rule: Host(`s3.zarantonello.dev`) && PathPrefix(`/rustfs`)
      traefik.http.routers.rustfs-console.service: rustfs-console
      traefik.http.routers.rustfs.entrypoints: http,https
      traefik.http.routers.rustfs.rule: Host(`s3.zarantonello.dev`)
      traefik.http.routers.rustfs.service: rustfs
      traefik.http.services.rustfs-console.loadbalancer.server.port: 9001
      traefik.http.services.rustfs.loadbalancer.server.port: 9000
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 30847:30847
    volumes:
      - $HOME/volumes/rustfs:/data
