networks:
  traefik_default:
    external: true

services:
  forgejo:
    cap_drop:
      - ALL
    env_file: .env
    environment:
      FORGEJO__admin__DISABLE_REGULAR_ORG_CREATION: false

      FORGEJO__api__ENABLE_SWAGGER: false

      FORGEJO__cache__ADAPTER: twoqueue
      # prettier-ignore
      FORGEJO__cache__HOST: "{ \"size\": 100, \"recent_ratio\": 0.25, \"ghost_ratio\": 0.5 }"

      FORGEJO__database__DB_TYPE: sqlite3
      FORGEJO__database__SQLITE_JOURNAL_MODE: WAL

      FORGEJO__mailer__ENABLED: true
      FORGEJO__mailer__FROM: Forgejo <git@zarantonello.dev>
      FORGEJO__mailer__PROTOCOL: smtps
      FORGEJO__mailer__SMTP_ADDR: mail.zarantonello.dev
      FORGEJO__mailer__SMTP_PORT: 465

      FORGEJO__openid__ENABLE_OPENID_SIGNIN: false

      FORGEJO__other__ENABLE_FEED: false

      FORGEJO__repository_0x2e_pull_request__DEFAULT_MERGE_STYLE: squash

      FORGEJO__repository__DEFAULT_PRIVATE: private
      FORGEJO__repository__DISABLED_REPO_UNITS: repo.ext_issues,repo.ext_wiki
      FORGEJO__repository__DISABLE_STARS: true

      # Disable when running for the first time, then re-enable it right after
      # installation has finished.
      FORGEJO__security__INSTALL_LOCK: true

      FORGEJO__server__DISABLE_SSH: true
      FORGEJO__server__DOMAIN: git.zarantonello.dev
      FORGEJO__server__ROOT_URL: https://git.zarantonello.dev/

      FORGEJO__service_0x2e_explore__DISABLE_USERS_PAGE: true

      FORGEJO__service__DISABLE_REGISTRATION: true
      # Require that user creates tokens to perform api operations, can't use password.
      FORGEJO__service__ENABLE_BASIC_AUTHENTICATION: false
      FORGEJO__service__ENABLE_NOTIFY_MAIL: true
      FORGEJO__service__REGISTER_MANUAL_CONFIRM: true

      FORGEJO__session__PROVIDER: db
    image: codeberg.org/forgejo/forgejo:14.0.4-rootless@sha256:bca6943cdd8a50f5befaf1d654bec32c9a3b6da400d23a77a829bd41f88a7263
    labels:
      monitoring.logs: true
      traefik.enable: true
      traefik.http.routers.forgejo.entrypoints: cloudflared,https,http
      traefik.http.routers.forgejo.rule: Host(`git.zarantonello.dev`)
      traefik.http.services.forgejo.loadbalancer.server.port: 3000
    networks:
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=1000,gid=1000
      - /var/lib/gitea/custom/conf:uid=1000,gid=1000
    user: 1000:1000
    volumes:
      - $HOME/volumes/forgejo:/var/lib/gitea
