configs:
  grafana:
    file: ./_configs/grafana.ini

networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  grafana:
    cap_drop:
      - ALL
    configs:
      - source: grafana
        target: /etc/grafana/grafana.ini
    env_file: .env
    environment:
      GF_INSTALL_PLUGINS: victoriametrics-logs-datasource,victoriametrics-metrics-datasource
    image: docker.io/grafana/grafana:12.3.2@sha256:ba93c9d192e58b23e064c7f501d453426ccf4a85065bf25b705ab1e98602bfb1
    labels:
      traefik.enable: true
      traefik.http.routers.grafana.entrypoints: https
      traefik.http.routers.grafana.rule: Host(`grafana.zarantonello.net`)
      traefik.http.services.grafana.loadbalancer.server.port: 3000
    networks:
      - traefik_default
      - alloy_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=31904,gid=31904
    user: 31904:31904
    volumes:
      - ./_configs/provisioning:/etc/grafana/provisioning:ro
      - $HOME/volumes/grafana:/var/lib/grafana
