configs:
  caddy:
    file: _configs/Caddyfile
  stalwart:
    file: _configs/stalwart.toml

networks:
  alloy_default:
    external: true
  stalwart_default:
    enable_ipv6: true
    name: stalwart_default
  traefik_default:
    external: true

services:
  # This only acts as an automatic certificate provider for stalwart.
  # Since stalwart's acme requires the config file to be writable :(.
  caddy:
    build: .
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: caddy
        target: /etc/caddy/Caddyfile
    env_file: .env
    networks:
      - stalwart_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /config:uid=54815,gid=54815
    user: 54815:54815
    volumes:
      - stalwart-caddy-data:/data

  stalwart:
    cap_add:
      - NET_BIND_SERVICE
    cap_drop:
      - ALL
    configs:
      - source: stalwart
        target: /opt/stalwart/etc/config.toml
    image: docker.io/stalwartlabs/stalwart:v0.15.5-alpine@sha256:0620ceba9165c104789d5cacb0aa209e7f16295f54edead631b1925b1ccc1ccf
    labels:
      monitoring.logs: true
      monitoring.metrics.path: /metrics/prometheus
      monitoring.metrics.port: 80
      traefik.enable: true
      traefik.http.routers.stalwart-public.entrypoints: cloudflared
      traefik.http.routers.stalwart-public.rule: (Host(`mta-sts.zarantonello.dev`) || Host(`mta-sts.zarantonello.net`)) && Path(`/.well-known/mta-sts.txt`)
      traefik.http.routers.stalwart-public.service: stalwart-public
      traefik.http.routers.stalwart.entrypoints: https
      traefik.http.routers.stalwart.rule: Host(`mail.zarantonello.dev`)
      traefik.http.routers.stalwart.service: stalwart
      traefik.http.services.stalwart-public.loadbalancer.server.port: 80
      traefik.http.services.stalwart.loadbalancer.server.port: 80
    networks:
      - alloy_default
      - stalwart_default
      - traefik_default
    ports:
      - 25:25
      - 465:465
      - 993:993
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=54815,gid=54815
    user: 54815:54815
    volumes:
      - $HOME/volumes/stalwart:/opt/stalwart
      - stalwart-caddy-data:/opt/caddy:ro

volumes:
  stalwart-caddy-data: {}
