networks:
  alloy_default:
    external: true
  traefik_default:
    external: true

services:
  cloudflared:
    cap_drop:
      - ALL
    command:
      - tunnel
      - run
    env_file: .env
    environment:
      NO_AUTOUPDATE: true
    image: docker.io/cloudflare/cloudflared:2026.3.0@sha256:6b599ca3e974349ead3286d178da61d291961182ec3fe9c505e1dd02c8ac31b0
    labels:
      monitoring.logs: true
      monitoring.metrics.port: 20241
    networks:
      - alloy_default
      - traefik_default
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 17026:17026
