services:
  minecraft:
    cap_drop:
      - ALL
    command:
      - java
      - -jar
      - fabric.jar
    image: docker.io/library/eclipse-temurin:25-jre@sha256:0a9c973778b03b88f39ccae4f8cc26022d84a3237a818cb98770369eb6c5daf9
    labels:
      monitoring.logs: true
    ports:
      - 25565:25565
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=36505,gid=36505
    user: 36505:36505
    volumes:
      - $HOME/volumes/minecraft:/data
    working_dir: /data
