services:
  minecraft:
    cap_drop:
      - ALL
    command:
      - java
      - -jar
      - fabric.jar
    image: docker.io/library/eclipse-temurin:26-jre@sha256:ebb7f006e9e5b8a5267b5910eb907922b99c251d702755e3cf3d9e2a2270090c
    labels:
      monitoring.logs: true
    ports:
      - 100.88.193.108:25565:25565
      - "[fd7a:115c:a1e0::6301:c1ac]:25565:25565"
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=36505,gid=36505
    user: 36505:36505
    volumes:
      - $HOME/volumes/minecraft:/data
    working_dir: /data
