services:
  minecraft:
    cap_drop:
      - ALL
    command:
      - java
      - -jar
      - fabric.jar
    image: docker.io/library/eclipse-temurin:26-jre@sha256:981cc979c518eb09e8a091cc9c52c3b4aa1e3d5d61b6fa07a5e09b34b6ba5374
    labels:
      monitoring.logs: true
    ports:
      - 100.88.193.108:25565:25565
      - "[fd7a:115c:a1e0::6301:c1ac]:25565:25565"
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp:uid=36505,gid=36505
    user: 36505:36505
    volumes:
      - $HOME/volumes/minecraft:/data
    working_dir: /data
